//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Client.ServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/RegisterClient", ReplyAction="http://tempuri.org/IService1/RegisterClientResponse")]
        void RegisterClient(string clientId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/RegisterClient", ReplyAction="http://tempuri.org/IService1/RegisterClientResponse")]
        System.Threading.Tasks.Task RegisterClientAsync(string clientId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Heartbeat", ReplyAction="http://tempuri.org/IService1/HeartbeatResponse")]
        void Heartbeat(string clientId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Heartbeat", ReplyAction="http://tempuri.org/IService1/HeartbeatResponse")]
        System.Threading.Tasks.Task HeartbeatAsync(string clientId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/MarkAsWorking", ReplyAction="http://tempuri.org/IService1/MarkAsWorkingResponse")]
        void MarkAsWorking(string clientId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/MarkAsWorking", ReplyAction="http://tempuri.org/IService1/MarkAsWorkingResponse")]
        System.Threading.Tasks.Task MarkAsWorkingAsync(string clientId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/MarkAsStandby", ReplyAction="http://tempuri.org/IService1/MarkAsStandbyResponse")]
        void MarkAsStandby(string clientId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/MarkAsStandby", ReplyAction="http://tempuri.org/IService1/MarkAsStandbyResponse")]
        System.Threading.Tasks.Task MarkAsStandbyAsync(string clientId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetClientStatus", ReplyAction="http://tempuri.org/IService1/GetClientStatusResponse")]
        string GetClientStatus(string clientId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetClientStatus", ReplyAction="http://tempuri.org/IService1/GetClientStatusResponse")]
        System.Threading.Tasks.Task<string> GetClientStatusAsync(string clientId);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : Client.ServiceReference.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<Client.ServiceReference.IService1>, Client.ServiceReference.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void RegisterClient(string clientId) {
            base.Channel.RegisterClient(clientId);
        }
        
        public System.Threading.Tasks.Task RegisterClientAsync(string clientId) {
            return base.Channel.RegisterClientAsync(clientId);
        }
        
        public void Heartbeat(string clientId) {
            base.Channel.Heartbeat(clientId);
        }
        
        public System.Threading.Tasks.Task HeartbeatAsync(string clientId) {
            return base.Channel.HeartbeatAsync(clientId);
        }
        
        public void MarkAsWorking(string clientId) {
            base.Channel.MarkAsWorking(clientId);
        }
        
        public System.Threading.Tasks.Task MarkAsWorkingAsync(string clientId) {
            return base.Channel.MarkAsWorkingAsync(clientId);
        }
        
        public void MarkAsStandby(string clientId) {
            base.Channel.MarkAsStandby(clientId);
        }
        
        public System.Threading.Tasks.Task MarkAsStandbyAsync(string clientId) {
            return base.Channel.MarkAsStandbyAsync(clientId);
        }
        
        public string GetClientStatus(string clientId) {
            return base.Channel.GetClientStatus(clientId);
        }
        
        public System.Threading.Tasks.Task<string> GetClientStatusAsync(string clientId) {
            return base.Channel.GetClientStatusAsync(clientId);
        }
    }
}
